services:

  enacit-dokuwiki:
    build:
      context: hosts/enacit-dokuwiki.epfl.ch
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    volumes:
      - enacit-dokuwiki-webshare:/config:rw
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enacit-dokuwiki.tls=true"
      - "traefik.http.routers.enacit-dokuwiki.rule=Host(`enacit-dokuwiki.epfl.ch`) && PathPrefix(`/`)"

volumes:
  enacit-dokuwiki-webshare:
    driver: local
    driver_opts:
      type: cifs
      o: username=${USER_ENACIT_WEBHOSTING_USERNAME},domain=${USER_ENACIT_WEBHOSTING_DOMAIN},password=${USER_ENACIT_WEBHOSTING_PASSWORD},uid=1000,gid=1000,rw
      device: "//enac1arch.epfl.ch/ENAC-IT/webhosting/enacit-dokuwiki/"
