services:

  enacit4r-cdn:
    image: nginx:1.25
    restart: unless-stopped
    environment:
      - NGINX_HOST=${HOSTNAME}
      - NGINX_PORT=80
      - DNS=${DNS}
      - S3_ENDPOINT_HOSTNAME=${S3_ENDPOINT_HOSTNAME}
      - S3_ENDPOINT_PROTOCOL=${S3_ENDPOINT_PROTOCOL}
      - BLUECITY_API_KEY=${BLUECITY_API_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_URBES_VIZ_BUCKET_NAME=${S3_URBES_VIZ_BUCKET_NAME}
    volumes:
      - ./hosts/enacit4r-cdn.epfl.ch/nginxTemplates:/etc/nginx/templates
      - ./hosts/enacit4r-cdn.epfl.ch/nginxCache:/etc/nginx/cache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enacit4rcdn.tls=true"
      - "traefik.http.routers.enacit4rcdn.rule=PathPrefix(`/`)"
      - "traefik.http.routers.enacit4rcdn.rule=Host(`enacit4r-cdn.epfl.ch`)"
      # - "traefik.http.services.enacit4rcdn.loadbalancer.server.port=80"
