services:

  diffurb:
    build:
      context: ./hosts/diffurb.epfl.ch
    volumes:
      - diffurb-webshare:/usr/local/apache2/htdocs:ro
      - ./hosts/diffurb.epfl.ch/apache.conf:/usr/local/apache2/conf/custom/diffurb.conf:ro
      - ./hosts/diffurb.epfl.ch/oidc.secret.conf:/usr/local/apache2/conf/oidc.secret.conf:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.diffurb.tls=true"
      - "traefik.http.routers.diffurb.rule=PathPrefix(`/`)"
      - "traefik.http.routers.diffurb.rule=Host(`diffurb.epfl.ch`)"
      # - "traefik.http.middlewares.diffurb-auth.basicauth.users=${DIFFURB_AUTH}"
      # - "traefik.http.routers.diffurb.middlewares=diffurb-auth"
volumes:
  diffurb-webshare:
    driver: local
    driver_opts:
      type: cifs
      o: username=${USER_ENACIT_WEBHOSTING_USERNAME},domain=${USER_ENACIT_WEBHOSTING_DOMAIN},password=${USER_ENACIT_WEBHOSTING_PASSWORD},uid=1000,gid=1000,ro
      device: "//enac1files.epfl.ch/LASUR/web/diffurb.epfl.ch/"
