services:

  enacrepo:
    image: nginx
    volumes:
      - enacrepo-webshare:/usr/share/nginx/html:ro
      - ./hosts/enacrepo.epfl.ch/nginx/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enacrepo.tls=true"
      - "traefik.http.routers.enacrepo.rule=PathPrefix(`/`)"
      - "traefik.http.routers.enacrepo.rule=Host(`enacrepo.epfl.ch`)"

volumes:
  enacrepo-webshare:
    driver: local
    driver_opts:
      type: cifs
      o: username=${USER_ENACIT_WEBHOSTING_USERNAME},domain=${USER_ENACIT_WEBHOSTING_DOMAIN},password=${USER_ENACIT_WEBHOSTING_PASSWORD},ro
      device: "//enac1arch.epfl.ch/ENAC-IT/webhosting/enacrepo/"
