services:

  enacsoft:
    build:
      context: hosts/enacsoft.epfl.ch
    user: "www-data:www-data"
    volumes:
      - enacsoft-webshare:/var/www/html:ro
      - ./hosts/enacsoft.epfl.ch/enacsoft.conf:/etc/apache2/sites-enabled/enacsoft.conf:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enacsoft.tls=true"
      - "traefik.http.routers.enacsoft.rule=PathPrefix(`/`)"
      - "traefik.http.routers.enacsoft.rule=Host(`enacsoft.epfl.ch`)"

volumes:
  enacsoft-webshare:
    driver: local
    driver_opts:
      type: cifs
      o: addr=enac1arch.epfl.ch,username=${USER_ENACIT_WEBHOSTING_USERNAME},domain=${USER_ENACIT_WEBHOSTING_DOMAIN},password=${USER_ENACIT_WEBHOSTING_PASSWORD},ro
      device: "//enac1arch.epfl.ch/ENAC-IT/webhosting/enacsoft/"
