services:

  resslabtools:
    build:
      context: hosts/resslabtools.epfl.ch
    volumes:
      - resslabtools-webshare:/var/www/html:ro
      - ./hosts/resslabtools.epfl.ch/php.ini:/usr/local/etc/php/php.ini:ro
      - ./hosts/resslabtools.epfl.ch/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
      - ./hosts/resslabtools.epfl.ch/revaliases:/etc/ssmtp/revaliases:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resslabtools.tls=true"
      - "traefik.http.routers.resslabtools.rule=PathPrefix(`/`)"
      - "traefik.http.routers.resslabtools.rule=Host(`resslabtools.epfl.ch`)"

volumes:
  resslabtools-webshare:
    driver: local
    driver_opts:
      type: cifs
      o: addr=enac1files.epfl.ch,username=${USER_ENACIT_WEBHOSTING_USERNAME},domain=${USER_ENACIT_WEBHOSTING_DOMAIN},password=${USER_ENACIT_WEBHOSTING_PASSWORD},ro
      device: "//enac1files.epfl.ch/RESSLAB/web/resslabtools.epfl.ch"
