services:

  diffurb:
    image: nginx:1.27-alpine
    volumes:
      - diffurb-webshare:/usr/share/nginx/html:ro
      - ./hosts/diffurb.epfl.ch/nginx/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.diffurb.tls=true"
      - "traefik.http.routers.diffurb.rule=PathPrefix(`/`)"
      - "traefik.http.routers.diffurb.rule=Host(`diffurb.epfl.ch`)"
      - "traefik.http.middlewares.diffurb-auth.basicauth.users=${DIFFURB_AUTH}"
      - "traefik.http.routers.diffurb.middlewares=diffurb-auth"
volumes:
  diffurb-webshare:
    driver: local
    driver_opts:
      type: cifs
      o: addr=enac1files.epfl.ch,username=${USER_ENACIT_WEBHOSTING_USERNAME},domain=${USER_ENACIT_WEBHOSTING_DOMAIN},password=${USER_ENACIT_WEBHOSTING_PASSWORD},ro
      device: "//enac1files.epfl.ch/LASUR/web/diffurb.epfl.ch/"
