include:
  - path:
      - docker-compose-base.yml
      - docker-compose-cnet-project.yml
      - docker-compose-diffurb.yml
      - docker-compose-echoserver.yml
      - docker-compose-enacit-dokuwiki.yml
      - docker-compose-enacit4r-cdn.yml
      - docker-compose-enacitarchives.yml
      - docker-compose-enacrepo.yml
      - docker-compose-enacsoft.yml
      - docker-compose-metalp.yml
      - docker-compose-resslabtools.yml
